-- Migration: Create QBR Packages Table
-- PRD-220: Intelligent QBR Generator
-- Created: 2026-01-29

-- QBR Packages table - stores generated QBR presentations
CREATE TABLE IF NOT EXISTS qbr_packages (
  id TEXT PRIMARY KEY,
  customer_id UUID NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL,
  quarter VARCHAR(2) NOT NULL CHECK (quarter IN ('Q1', 'Q2', 'Q3', 'Q4')),
  year INTEGER NOT NULL CHECK (year >= 2020 AND year <= 2100),
  status VARCHAR(20) NOT NULL DEFAULT 'generating'
    CHECK (status IN ('generating', 'draft', 'ready', 'presented')),
  presentation_id TEXT,
  presentation_url TEXT,
  document_id TEXT,
  document_url TEXT,
  content JSONB,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  presented_at TIMESTAMPTZ,
  approved_by TEXT,
  approved_at TIMESTAMPTZ,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Ensure unique QBR per customer per quarter
  UNIQUE(customer_id, quarter, year)
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_qbr_packages_customer ON qbr_packages(customer_id);
CREATE INDEX IF NOT EXISTS idx_qbr_packages_status ON qbr_packages(status);
CREATE INDEX IF NOT EXISTS idx_qbr_packages_quarter_year ON qbr_packages(year DESC, quarter DESC);
CREATE INDEX IF NOT EXISTS idx_qbr_packages_generated ON qbr_packages(generated_at DESC);

-- QBR feedback table - stores CSM feedback on generated content
CREATE TABLE IF NOT EXISTS qbr_feedback (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  qbr_id TEXT NOT NULL REFERENCES qbr_packages(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL,
  section VARCHAR(50),
  feedback_type VARCHAR(20) NOT NULL CHECK (feedback_type IN ('positive', 'negative', 'suggestion')),
  feedback TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_qbr_feedback_qbr ON qbr_feedback(qbr_id);

-- QBR templates table - stores custom QBR templates per organization
CREATE TABLE IF NOT EXISTS qbr_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(100) NOT NULL,
  description TEXT,
  sections JSONB NOT NULL,
  is_default BOOLEAN DEFAULT FALSE,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Insert default templates
INSERT INTO qbr_templates (name, description, sections, is_default)
VALUES
  (
    'Standard QBR',
    'Comprehensive quarterly business review with all sections',
    '["executive_summary", "partnership_health", "usage_metrics", "key_achievements", "challenges_addressed", "support_summary", "product_roadmap", "recommendations", "next_quarter_goals"]',
    true
  ),
  (
    'Executive Summary',
    'High-level overview for executive stakeholders',
    '["executive_summary", "partnership_health", "key_achievements", "strategic_initiatives"]',
    false
  ),
  (
    'Tactical Review',
    'Detailed operational review',
    '["usage_metrics", "support_summary", "challenges_addressed", "recommendations", "next_quarter_goals"]',
    false
  )
ON CONFLICT DO NOTHING;

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_qbr_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-update updated_at
DROP TRIGGER IF EXISTS qbr_packages_updated_at ON qbr_packages;
CREATE TRIGGER qbr_packages_updated_at
  BEFORE UPDATE ON qbr_packages
  FOR EACH ROW
  EXECUTE FUNCTION update_qbr_updated_at();

-- RLS Policies (assuming Supabase)
ALTER TABLE qbr_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE qbr_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE qbr_templates ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to view their QBRs
CREATE POLICY "Users can view QBRs" ON qbr_packages
  FOR SELECT
  USING (true);

-- Allow authenticated users to create QBRs
CREATE POLICY "Users can create QBRs" ON qbr_packages
  FOR INSERT
  WITH CHECK (true);

-- Allow users to update their own QBRs
CREATE POLICY "Users can update QBRs" ON qbr_packages
  FOR UPDATE
  USING (true);

-- Feedback policies
CREATE POLICY "Users can view feedback" ON qbr_feedback
  FOR SELECT
  USING (true);

CREATE POLICY "Users can create feedback" ON qbr_feedback
  FOR INSERT
  WITH CHECK (true);

-- Template policies
CREATE POLICY "Users can view templates" ON qbr_templates
  FOR SELECT
  USING (true);

COMMENT ON TABLE qbr_packages IS 'PRD-220: Stores AI-generated QBR presentations and documents';
COMMENT ON COLUMN qbr_packages.content IS 'JSON containing all QBR section content generated by AI';
