# Google Cloud Build configuration for CSCX.AI

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cscx-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cscx-api:latest'
      - '.'

  # Step 2: Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/cscx-api:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/cscx-api:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cscx-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cscx-api:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-secrets'
      - 'GEMINI_API_KEY=GEMINI_API_KEY:latest,ANTHROPIC_API_KEY=ANTHROPIC_API_KEY:latest,SUPABASE_URL=SUPABASE_URL:latest,SUPABASE_SERVICE_KEY=SUPABASE_SERVICE_KEY:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest'
      - '--set-env-vars'
      - 'NODE_ENV=production'

# Substitutions (can be overridden)
substitutions:
  _REGION: us-central1

# Build options
options:
  logging: CLOUD_LOGGING_ONLY

# Images to store
images:
  - 'gcr.io/$PROJECT_ID/cscx-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/cscx-api:latest'

# Build timeout
timeout: '1200s'
