/**
 * Health Insights Types
 *
 * Type definitions for AI-powered health score insights and recommendations.
 */

// Risk severity levels for insights
export type InsightSeverity = 'info' | 'warning' | 'critical' | 'positive';

// Categories of health insights
export type InsightCategory =
  | 'usage'
  | 'engagement'
  | 'support'
  | 'business'
  | 'stakeholder'
  | 'renewal'
  | 'opportunity';

// Health trend direction
export type TrendDirection = 'improving' | 'stable' | 'declining' | 'volatile';

/**
 * Individual insight generated by AI
 */
export interface HealthInsight {
  id: string;
  category: InsightCategory;
  severity: InsightSeverity;
  title: string;
  description: string;
  impact: string;
  recommendation: string;
  confidence: number; // 0-100
  dataPoints: string[]; // Supporting data points
  timeframe?: string; // When this insight is most relevant
}

/**
 * Predicted health trajectory point
 */
export interface HealthPredictionPoint {
  daysAhead: number;
  predictedScore: number;
  confidenceInterval: {
    low: number;
    high: number;
  };
  keyFactors: string[];
}

/**
 * Intervention recommendation with impact modeling
 */
export interface InterventionRecommendation {
  intervention: string;
  description: string;
  expectedHealthImpact: number; // Positive number = improvement
  confidence: number; // 0-100
  timeToImpactDays: number;
  effort: 'low' | 'medium' | 'high';
  priority: number; // 1-5, 1 being highest
  category: InsightCategory;
}

/**
 * Health score component breakdown
 */
export interface HealthScoreBreakdown {
  usage: number;
  engagement: number;
  risk: number;
  business: number;
  overall: number;
}

/**
 * Historical health data point
 */
export interface HealthHistoryPoint {
  date: string;
  score: number;
  components?: HealthScoreBreakdown;
}

/**
 * Complete health insights response
 */
export interface HealthInsightsResponse {
  customerId: string;
  customerName: string;
  generatedAt: string;

  // Current state
  currentHealth: number;
  previousHealth: number | null;
  trend: TrendDirection;
  scoreBreakdown: HealthScoreBreakdown;

  // AI-generated insights
  insights: HealthInsight[];

  // Predictions
  predictions: HealthPredictionPoint[];

  // Recommended actions
  interventions: InterventionRecommendation[];

  // Summary
  executiveSummary: string;
  riskLevel: 'low' | 'medium' | 'high' | 'critical';
  arrAtRisk: number;
  daysToRenewal: number | null;

  // Metadata
  confidence: number;
  dataQuality: 'poor' | 'fair' | 'good' | 'excellent';
  lastDataUpdate: string | null;
}

/**
 * Request parameters for health insights
 */
export interface HealthInsightsRequest {
  customerId: string;
  includeHistory?: boolean;
  includePredictions?: boolean;
  predictionHorizons?: number[]; // Days ahead [30, 60, 90]
}

/**
 * Feedback on insight quality
 */
export interface InsightFeedback {
  insightId: string;
  helpful: boolean;
  actionTaken: boolean;
  notes?: string;
}

/**
 * Portfolio-level health insights summary
 */
export interface PortfolioHealthSummary {
  totalCustomers: number;
  avgHealth: number;
  healthDistribution: {
    critical: number; // < 40
    atRisk: number;   // 40-59
    healthy: number;  // 60-79
    excellent: number; // 80+
  };
  trendingDown: number;
  trendingUp: number;
  totalArrAtRisk: number;
  topRisks: Array<{
    customerId: string;
    customerName: string;
    health: number;
    arr: number;
    daysToRenewal: number | null;
    topInsight: string;
  }>;
  recommendedFocus: string[];
}
