-- PRD: Context-Aware Agentic Document Generation (CADG)
-- Migration to create generated_artifacts table for tracking all generated outputs

-- Create generated_artifacts table
CREATE TABLE IF NOT EXISTS generated_artifacts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    plan_id UUID REFERENCES execution_plans(id) ON DELETE SET NULL,
    customer_id UUID REFERENCES customers(id) ON DELETE SET NULL,
    user_id UUID REFERENCES users(id) ON DELETE SET NULL,

    -- Artifact identification
    artifact_type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,

    -- Storage references
    drive_file_id VARCHAR(255),
    drive_url TEXT,

    -- Content
    preview_markdown TEXT,
    content_hash VARCHAR(64),

    -- Metadata
    sources_used JSONB,
    generation_duration_ms INTEGER,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_generated_artifacts_plan_id ON generated_artifacts(plan_id);
CREATE INDEX IF NOT EXISTS idx_generated_artifacts_customer_id ON generated_artifacts(customer_id);
CREATE INDEX IF NOT EXISTS idx_generated_artifacts_user_id ON generated_artifacts(user_id);
CREATE INDEX IF NOT EXISTS idx_generated_artifacts_artifact_type ON generated_artifacts(artifact_type);
CREATE INDEX IF NOT EXISTS idx_generated_artifacts_created_at ON generated_artifacts(created_at);

-- Composite index for customer artifact history
CREATE INDEX IF NOT EXISTS idx_generated_artifacts_customer_type ON generated_artifacts(customer_id, artifact_type);

-- GIN index for searching sources
CREATE INDEX IF NOT EXISTS idx_generated_artifacts_sources ON generated_artifacts USING GIN(sources_used);

-- Comments
COMMENT ON TABLE generated_artifacts IS 'Tracks all artifacts generated by the CADG system';
COMMENT ON COLUMN generated_artifacts.artifact_type IS 'Type of artifact: slides, docs, sheets, email, chat';
COMMENT ON COLUMN generated_artifacts.drive_file_id IS 'Google Drive file ID for stored artifacts';
COMMENT ON COLUMN generated_artifacts.drive_url IS 'Direct URL to the artifact in Google Drive';
COMMENT ON COLUMN generated_artifacts.preview_markdown IS 'Markdown preview of the artifact for chat display';
COMMENT ON COLUMN generated_artifacts.content_hash IS 'SHA-256 hash of content for deduplication';
COMMENT ON COLUMN generated_artifacts.sources_used IS 'Array of sources used to generate this artifact';
COMMENT ON COLUMN generated_artifacts.generation_duration_ms IS 'Time taken to generate the artifact in milliseconds';

-- Enable RLS
ALTER TABLE generated_artifacts ENABLE ROW LEVEL SECURITY;

-- RLS policies
CREATE POLICY "Users can view own artifacts" ON generated_artifacts
    FOR SELECT
    USING (user_id = auth.uid() OR auth.role() = 'service_role');

CREATE POLICY "Users can create own artifacts" ON generated_artifacts
    FOR INSERT
    WITH CHECK (user_id = auth.uid() OR auth.role() = 'service_role');

-- Grant permissions
GRANT SELECT, INSERT ON generated_artifacts TO authenticated;

-- Create view for artifact analytics
CREATE OR REPLACE VIEW artifact_analytics AS
SELECT
    DATE_TRUNC('day', created_at) as date,
    artifact_type,
    COUNT(*) as total_artifacts,
    AVG(generation_duration_ms) as avg_duration_ms,
    COUNT(DISTINCT customer_id) as unique_customers,
    COUNT(DISTINCT user_id) as unique_users
FROM generated_artifacts
WHERE created_at >= NOW() - INTERVAL '30 days'
GROUP BY DATE_TRUNC('day', created_at), artifact_type
ORDER BY date DESC, artifact_type;

COMMENT ON VIEW artifact_analytics IS 'Analytics view for artifact generation metrics';

GRANT SELECT ON artifact_analytics TO authenticated;
