-- PRD: Knowledge Base Population & CSM Capability Index
-- Seed initial capabilities for the CADG system

-- Clear existing capabilities for re-seeding
DELETE FROM capabilities;

-- Document Generation Capabilities
INSERT INTO capabilities (id, name, category, description, trigger_patterns, keywords, example_prompts, required_inputs, outputs, execution, related_capabilities) VALUES
('qbr_generation', 'QBR Generation', 'document_generation', 'Generate a comprehensive Quarterly Business Review presentation',
 '["build me a qbr", "create a qbr", "generate quarterly business review", "prepare qbr deck", "make a qbr presentation", "qbr for {customer}"]'::jsonb,
 ARRAY['qbr', 'quarterly', 'business review', 'deck', 'presentation', 'quarterly review'],
 '["Build me a QBR for Acme Corp", "Create a Q4 business review deck", "Generate a QBR focusing on expansion opportunities"]'::jsonb,
 '[{"name": "customerId", "type": "uuid", "source": "context", "required": true}, {"name": "quarter", "type": "string", "source": "user", "required": false}]'::jsonb,
 '[{"type": "slides", "format": "google_slides", "description": "QBR presentation deck"}, {"type": "chat", "format": "markdown", "description": "Executive summary preview"}]'::jsonb,
 '{"service": "QBRGeneratorService", "method": "generateQBR", "requiresApproval": true, "estimatedDuration": "30-60 seconds"}'::jsonb,
 ARRAY['health_analysis', 'metrics_report', 'meeting_prep']),

('health_analysis', 'Health Analysis', 'data_analysis', 'Analyze customer health score trends and contributing factors',
 '["analyze health", "why is health dropping", "health score analysis", "what happened to health"]'::jsonb,
 ARRAY['health', 'score', 'analysis', 'dropping', 'declining', 'improving', 'trend'],
 '["Why is Acme''s health score dropping?", "Analyze the health trend for this customer", "What''s causing the health decline?"]'::jsonb,
 '[{"name": "customerId", "type": "uuid", "source": "context", "required": true}, {"name": "period", "type": "string", "source": "user", "required": false}]'::jsonb,
 '[{"type": "chat", "format": "markdown", "description": "Health analysis report"}]'::jsonb,
 '{"service": "HealthAnalysisService", "method": "analyzeHealth", "requiresApproval": false, "estimatedDuration": "10-20 seconds"}'::jsonb,
 ARRAY['risk_assessment', 'engagement_report']),

('email_drafting', 'Email Drafting', 'communication', 'Draft professional customer emails for various situations',
 '["draft email", "write email", "compose email", "email to {customer}", "send email"]'::jsonb,
 ARRAY['email', 'draft', 'write', 'compose', 'message', 'send', 'follow-up', 'outreach'],
 '["Draft a check-in email for Acme", "Write a renewal reminder email", "Compose a QBR invitation"]'::jsonb,
 '[{"name": "customerId", "type": "uuid", "source": "context", "required": true}, {"name": "emailType", "type": "string", "source": "user", "required": false}]'::jsonb,
 '[{"type": "email", "format": "markdown", "description": "Email draft"}]'::jsonb,
 '{"service": "EmailDraftService", "method": "draftEmail", "requiresApproval": true, "estimatedDuration": "15-30 seconds"}'::jsonb,
 ARRAY['meeting_prep', 'customer_research']),

('meeting_prep', 'Meeting Prep', 'scheduling', 'Prepare briefing materials for upcoming customer meetings',
 '["prep for meeting", "prepare for call", "meeting prep", "brief me for", "get me ready for"]'::jsonb,
 ARRAY['meeting', 'prep', 'prepare', 'call', 'brief', 'ready', 'talking points', 'agenda'],
 '["Prep me for tomorrow''s call with Acme", "Prepare briefing for the QBR meeting", "Get me ready for the renewal discussion"]'::jsonb,
 '[{"name": "customerId", "type": "uuid", "source": "context", "required": true}, {"name": "meetingType", "type": "string", "source": "user", "required": false}]'::jsonb,
 '[{"type": "chat", "format": "markdown", "description": "Meeting prep brief"}]'::jsonb,
 '{"service": "MeetingPrepService", "method": "prepareBrief", "requiresApproval": false, "estimatedDuration": "20-30 seconds"}'::jsonb,
 ARRAY['customer_research', 'risk_assessment']),

('risk_assessment', 'Risk Assessment', 'risk_management', 'Assess and analyze customer churn risk signals',
 '["assess risk", "what are the risks", "churn risk", "risk analysis", "should I worry"]'::jsonb,
 ARRAY['risk', 'churn', 'warning', 'signals', 'assessment', 'worry', 'concern', 'red flag'],
 '["What are the risks for Acme?", "Assess churn risk for this customer", "Should I be worried about this account?"]'::jsonb,
 '[{"name": "customerId", "type": "uuid", "source": "context", "required": true}]'::jsonb,
 '[{"type": "chat", "format": "markdown", "description": "Risk assessment report"}]'::jsonb,
 '{"service": "RiskAssessmentService", "method": "assessRisk", "requiresApproval": false, "estimatedDuration": "15-25 seconds"}'::jsonb,
 ARRAY['health_analysis', 'renewal_forecast']),

('renewal_forecast', 'Renewal Forecast', 'renewal', 'Forecast renewal probability and recommend actions',
 '["renewal forecast", "predict renewal", "renewal probability", "will they renew"]'::jsonb,
 ARRAY['renewal', 'forecast', 'predict', 'probability', 'renew', 'churn'],
 '["What''s the renewal forecast for Acme?", "Predict renewal probability", "Will this customer renew?"]'::jsonb,
 '[{"name": "customerId", "type": "uuid", "source": "context", "required": true}]'::jsonb,
 '[{"type": "chat", "format": "markdown", "description": "Renewal forecast report"}]'::jsonb,
 '{"service": "RenewalForecastService", "method": "forecast", "requiresApproval": false, "estimatedDuration": "10-20 seconds"}'::jsonb,
 ARRAY['risk_assessment', 'expansion_analysis']),

('expansion_analysis', 'Expansion Analysis', 'expansion', 'Identify and analyze expansion opportunities',
 '["expansion opportunities", "upsell analysis", "growth potential", "cross-sell opportunities"]'::jsonb,
 ARRAY['expansion', 'upsell', 'cross-sell', 'growth', 'opportunity', 'potential', 'increase'],
 '["What expansion opportunities exist for Acme?", "Analyze upsell potential", "Where can we grow this account?"]'::jsonb,
 '[{"name": "customerId", "type": "uuid", "source": "context", "required": true}]'::jsonb,
 '[{"type": "docs", "format": "google_docs", "description": "Expansion analysis document"}]'::jsonb,
 '{"service": "ExpansionService", "method": "analyzeOpportunities", "requiresApproval": false, "estimatedDuration": "20-30 seconds"}'::jsonb,
 ARRAY['renewal_forecast', 'account_plan']),

('onboarding_plan', 'Onboarding Plan', 'onboarding', 'Create comprehensive customer onboarding plans',
 '["create onboarding plan", "onboarding for {customer}", "new customer setup", "kickoff plan"]'::jsonb,
 ARRAY['onboarding', 'plan', 'kickoff', 'setup', 'new customer', 'welcome'],
 '["Create an onboarding plan for Acme", "Build kickoff agenda", "Set up new customer onboarding"]'::jsonb,
 '[{"name": "customerId", "type": "uuid", "source": "context", "required": true}]'::jsonb,
 '[{"type": "docs", "format": "google_docs", "description": "Onboarding plan document"}]'::jsonb,
 '{"service": "OnboardingService", "method": "createPlan", "requiresApproval": true, "estimatedDuration": "30-45 seconds"}'::jsonb,
 ARRAY['success_plan', 'meeting_prep']),

('success_plan', 'Success Plan', 'document_generation', 'Create customer success plans with goals and milestones',
 '["create success plan", "success roadmap", "customer goals"]'::jsonb,
 ARRAY['success', 'plan', 'goals', 'milestones', 'roadmap', 'objectives'],
 '["Create a success plan for Acme", "Build a customer roadmap", "Define success milestones"]'::jsonb,
 '[{"name": "customerId", "type": "uuid", "source": "context", "required": true}]'::jsonb,
 '[{"type": "docs", "format": "google_docs", "description": "Success plan document"}]'::jsonb,
 '{"service": "SuccessPlanService", "method": "createPlan", "requiresApproval": true, "estimatedDuration": "30-45 seconds"}'::jsonb,
 ARRAY['account_plan', 'onboarding_plan']),

('account_plan', 'Account Plan', 'document_generation', 'Create strategic account plans',
 '["create account plan", "strategic plan", "account strategy"]'::jsonb,
 ARRAY['account', 'plan', 'strategic', 'strategy', 'planning'],
 '["Create an account plan for Acme", "Build strategic account plan", "Develop account strategy"]'::jsonb,
 '[{"name": "customerId", "type": "uuid", "source": "context", "required": true}]'::jsonb,
 '[{"type": "docs", "format": "google_docs", "description": "Account plan document"}]'::jsonb,
 '{"service": "AccountPlanService", "method": "createPlan", "requiresApproval": true, "estimatedDuration": "30-45 seconds"}'::jsonb,
 ARRAY['success_plan', 'expansion_analysis']),

('customer_research', 'Customer Research', 'research', 'Research company background and stakeholders',
 '["research {customer}", "company background", "stakeholder mapping", "learn about"]'::jsonb,
 ARRAY['research', 'company', 'background', 'stakeholder', 'learn', 'intel', 'information'],
 '["Research Acme Corp", "Find company background", "Map key stakeholders"]'::jsonb,
 '[{"name": "customerId", "type": "uuid", "source": "context", "required": true}]'::jsonb,
 '[{"type": "chat", "format": "markdown", "description": "Research summary"}]'::jsonb,
 '{"service": "ResearchService", "method": "researchCustomer", "requiresApproval": false, "estimatedDuration": "15-30 seconds"}'::jsonb,
 ARRAY['stakeholder_mapping', 'meeting_prep']),

('stakeholder_mapping', 'Stakeholder Mapping', 'research', 'Map customer stakeholders and relationships',
 '["map stakeholders", "who are the key contacts", "org chart", "decision makers"]'::jsonb,
 ARRAY['stakeholder', 'map', 'contacts', 'org', 'chart', 'decision', 'maker', 'champion'],
 '["Map stakeholders at Acme", "Who are the key contacts?", "Show me the decision makers"]'::jsonb,
 '[{"name": "customerId", "type": "uuid", "source": "context", "required": true}]'::jsonb,
 '[{"type": "chat", "format": "markdown", "description": "Stakeholder map"}]'::jsonb,
 '{"service": "StakeholderService", "method": "mapStakeholders", "requiresApproval": false, "estimatedDuration": "15-25 seconds"}'::jsonb,
 ARRAY['customer_research', 'expansion_analysis']),

('deck_creation', 'Deck Creation', 'document_generation', 'Create presentation decks for various purposes',
 '["create deck", "build presentation", "make slides", "executive briefing deck"]'::jsonb,
 ARRAY['deck', 'presentation', 'slides', 'briefing', 'powerpoint'],
 '["Create an executive briefing deck", "Build a presentation for the board", "Make slides for the meeting"]'::jsonb,
 '[{"name": "customerId", "type": "uuid", "source": "context", "required": false}, {"name": "purpose", "type": "string", "source": "user", "required": true}]'::jsonb,
 '[{"type": "slides", "format": "google_slides", "description": "Presentation deck"}]'::jsonb,
 '{"service": "DeckCreationService", "method": "createDeck", "requiresApproval": true, "estimatedDuration": "45-60 seconds"}'::jsonb,
 ARRAY['qbr_generation', 'meeting_prep']),

('document_creation', 'Document Creation', 'document_generation', 'Create general documents and reports',
 '["create document", "write report", "make doc"]'::jsonb,
 ARRAY['document', 'doc', 'report', 'write', 'create'],
 '["Create a summary document", "Write a report", "Make a project document"]'::jsonb,
 '[{"name": "customerId", "type": "uuid", "source": "context", "required": false}, {"name": "documentType", "type": "string", "source": "user", "required": true}]'::jsonb,
 '[{"type": "docs", "format": "google_docs", "description": "Document"}]'::jsonb,
 '{"service": "DocumentService", "method": "createDocument", "requiresApproval": true, "estimatedDuration": "30-45 seconds"}'::jsonb,
 ARRAY['success_plan', 'account_plan']),

('data_analysis', 'Data Analysis', 'data_analysis', 'Analyze metrics and data trends',
 '["analyze data", "show metrics", "data analysis", "breakdown of"]'::jsonb,
 ARRAY['analyze', 'data', 'metrics', 'trends', 'breakdown', 'analysis', 'report'],
 '["Analyze engagement data", "Show me the metrics breakdown", "What do the trends show?"]'::jsonb,
 '[{"name": "customerId", "type": "uuid", "source": "context", "required": false}, {"name": "dataType", "type": "string", "source": "user", "required": false}]'::jsonb,
 '[{"type": "chat", "format": "markdown", "description": "Analysis report"}]'::jsonb,
 '{"service": "DataAnalysisService", "method": "analyze", "requiresApproval": false, "estimatedDuration": "15-30 seconds"}'::jsonb,
 ARRAY['health_analysis', 'portfolio_review']),

('portfolio_review', 'Portfolio Review', 'reporting', 'Review portfolio health and trends',
 '["portfolio review", "my accounts", "portfolio health", "book of business"]'::jsonb,
 ARRAY['portfolio', 'review', 'accounts', 'book', 'business', 'overview'],
 '["Review my portfolio", "How are my accounts doing?", "Portfolio health overview"]'::jsonb,
 '[{"name": "userId", "type": "uuid", "source": "context", "required": true}]'::jsonb,
 '[{"type": "chat", "format": "markdown", "description": "Portfolio review"}]'::jsonb,
 '{"service": "PortfolioService", "method": "reviewPortfolio", "requiresApproval": false, "estimatedDuration": "20-30 seconds"}'::jsonb,
 ARRAY['risk_assessment', 'renewal_forecast']),

('cohort_comparison', 'Cohort Comparison', 'data_analysis', 'Compare customer to their cohort',
 '["compare to cohort", "benchmark against", "how do they compare", "peer comparison"]'::jsonb,
 ARRAY['compare', 'cohort', 'benchmark', 'peer', 'similar', 'comparison'],
 '["Compare Acme to their cohort", "How do they benchmark?", "Peer comparison for this customer"]'::jsonb,
 '[{"name": "customerId", "type": "uuid", "source": "context", "required": true}, {"name": "cohortBy", "type": "string", "source": "user", "required": false}]'::jsonb,
 '[{"type": "chat", "format": "markdown", "description": "Cohort comparison"}]'::jsonb,
 '{"service": "CohortService", "method": "compare", "requiresApproval": false, "estimatedDuration": "15-25 seconds"}'::jsonb,
 ARRAY['data_analysis', 'health_analysis']),

('churn_analysis', 'Churn Analysis', 'risk_management', 'Deep analysis of churn indicators',
 '["churn analysis", "why might they churn", "churn indicators"]'::jsonb,
 ARRAY['churn', 'analysis', 'indicators', 'leave', 'cancel'],
 '["Run churn analysis for Acme", "What are the churn indicators?", "Why might they leave?"]'::jsonb,
 '[{"name": "customerId", "type": "uuid", "source": "context", "required": true}]'::jsonb,
 '[{"type": "chat", "format": "markdown", "description": "Churn analysis"}]'::jsonb,
 '{"service": "ChurnService", "method": "analyze", "requiresApproval": false, "estimatedDuration": "15-25 seconds"}'::jsonb,
 ARRAY['risk_assessment', 'save_play']),

('engagement_report', 'Engagement Report', 'reporting', 'Generate engagement metrics report',
 '["engagement report", "how engaged are they", "usage report"]'::jsonb,
 ARRAY['engagement', 'report', 'usage', 'activity', 'adoption'],
 '["Generate engagement report for Acme", "How engaged are they?", "Show me their usage"]'::jsonb,
 '[{"name": "customerId", "type": "uuid", "source": "context", "required": true}]'::jsonb,
 '[{"type": "chat", "format": "markdown", "description": "Engagement report"}]'::jsonb,
 '{"service": "EngagementService", "method": "generateReport", "requiresApproval": false, "estimatedDuration": "15-20 seconds"}'::jsonb,
 ARRAY['health_analysis', 'data_analysis']),

('nps_analysis', 'NPS Analysis', 'data_analysis', 'Analyze NPS scores and feedback',
 '["nps analysis", "nps score", "customer satisfaction", "feedback analysis"]'::jsonb,
 ARRAY['nps', 'score', 'satisfaction', 'feedback', 'survey'],
 '["Analyze NPS for Acme", "What''s their satisfaction level?", "Review their feedback"]'::jsonb,
 '[{"name": "customerId", "type": "uuid", "source": "context", "required": true}]'::jsonb,
 '[{"type": "chat", "format": "markdown", "description": "NPS analysis"}]'::jsonb,
 '{"service": "NPSService", "method": "analyze", "requiresApproval": false, "estimatedDuration": "10-20 seconds"}'::jsonb,
 ARRAY['health_analysis', 'risk_assessment']);

-- Create indexes for the new data
ANALYZE capabilities;
